### PR TITLE
tweak(platform): Remove unused supabase services in docker compose

### PR DESCRIPTION
**Pull request by aarushik93**
### Background

Now that we've added supabase, we have soo many services, many that we dont use. Unpick and remove the ones we don't need.

### Changes 🏗️

Removed realtime, storage, imgproxy, meta, functions

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

### CODE REVIEW

**Comment by ntindle** [comment]
imo set this up with profiles https://docs.docker.com/compose/how-tos/profiles/

**Review by ntindle — CHANGES_REQUESTED** [review]
Use profiles

**Comment by aarushik93** [comment]
@ntindle why though? in which situation do we use all of these? even for local dev we don't need all of them

**Review by majdyz — APPROVED** [review]
Love this ❤️ 
Can we make the `db` service depends on other services so 
`docker compose db up` brings up everything ?

**Comment by ntindle** [comment]
That’s totally fair, earlier Nick was wrong

**Pull request merged**
