### PR TITLE
Data ingestion option for startup menu

### PR DESCRIPTION
**Pull request by bassie661**
Adds a menu option so the user can start data ingestion directly from the command prompt / startup-menu.

This PR adds a new menu item so the user can choose the option to ingest data, after choosing "" the menu presents an overview of the directories and files in the workspace_directory. When the user selects a file it will automatically by passed on to the ingest_file function, when the user chooses a directory, the chosen directory wil be passed on to the ingest_directory function.

This PR relies on PR #4646 .

* I didn't take over the configure_logger function from data_ingestion.py

image

### Test Plan
- still need to write pytests

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run the commands against my code to ensure it passes our linters.

### CODE REVIEW

**Comment by ntindle** [comment]
@Pwuts are we ready to do this before memory is up and functional?

**Comment by Boostrix** [comment]
This seems like an excellent idea to me, and like a usability improvement - and we've previously had support for pre-seeding/ingesting data too

**Comment by Pwuts** [comment]
Blocked by #4646

**Comment by Pwuts** [comment]
> @Pwuts are we ready to do this before memory is up and functional?

nope

**Comment by bassie661** [comment]
so autogpt is dead ?

**Comment by Pwuts** [comment]
> Ridiculous for the amount of work put into this menu option.

It definitely hurts to close PRs like this. We're sorry it happened this way. Data ingestion is still something we need, but our system wasn't ready for it at the time and we were overloaded with maintenance and feature requests. This PR is now so far out of date that we can't integrate it anymore without a LOT of work, and we currently have other priorities.

When we get to data ingestion in the future, this PR will serve as inspiration.

I'm sure this isn't very satisfying for you, especially after so much work. We do our best to not let this happen in the future and are working on OSS tooling to not let PRs like this fall through the cracks.

**Pull request closed without merging**
