### PR TITLE
Add a kill switch feature: This will disable the agent running in con…

### PR DESCRIPTION
**Pull request by rain-1**
### Changes

Add a kill switch feature: This will disable the agent running in continuous mode if a certain canary string is missing from a webpage.

There is a global kill switch intended to be used by the project leader. And a local kill switch intended to be used by the user of the software. These things are optional but an extra warning is printed if continuous mode is launched without one. They only abort execution when continuous mode is being used. If the website cannot be accessed this errs on the side of safety and halts execution.

4 new command line flags are added: --{global,local}-kill-switch{,-canary} to configure the URL for the kill switch web pages and the canary strings. It is intended that some defaults be set for the global kill switch by an Auto-GPT safety team.

### Documentation
The command line flags have self descriptions in them.

### Test Plan
I tested it by running the program in continuous mode proving a canary that was in my web page, and one that was not.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ x I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes : The precommit hook made a change to one line of code that I did not work on.

### CODE REVIEW

**Comment by rain-1** [comment]
I have written out some reasoning for why I made this PR here https://gist.github.com/rain-1/cc67caa8873ee38098aefb0f35f46014

**Review by nponeccop — DISMISSED** [review]

**Comment by nponeccop** [comment]
@rain-1 There are conflicts now

**Comment by rain-1** [comment]
I've done

```
git checkout master
git pull
git checkout kill_switch
git merge master
```

hope I did that correctly.

**Comment by rain-1** [comment]
Not sure why this closed. The merge I did seemed wrong. So I went to https://github.com/rain-1/Auto-GPT/tree/kill_switch and clicked to drop the merge commit I did then Sync Fork and it seems to have screwed something up.

**Comment by rain-1** [comment]
Okay, I've properly merged in the changes from master into my branch and fixed that all up.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by rain-1** [comment]
Thank you for the response @p-i-

Is there an interest in merging this? I have refactored it several times to keep up with the repo.

**Comment by anonhostpi** [comment]
Related: #1472 and #3083

**Comment by Pwuts** [comment]
@ntindle if we decide to take this in, I'm willing to fix it up if needed

**Pull request closed without merging**
