### PR TITLE
feat(platform): Introduced Agent Execution Block

### PR DESCRIPTION
**Pull request by majdyz**
### Background

This change depends on: https://github.com/Significant-Gravitas/AutoGPT/pull/8526

Now the created agents will be available on the block list and can be used as part of the other graph.

image
image

### Changes 🏗️

Introduced Agent execution as a block/node in a graph.

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

Only for the new autogpt platform, currently in autogpt_platform/

If you're making configuration or infrastructure changes, please remember to check you've updated the related infrastructure code in the autogpt_platform/infra folder.

Examples of such changes might include: 

- Changing ports
- Adding new services that need to communicate with each other
- Secrets or environment variable changes
- New or infrastructure changes such as databases

### CODE REVIEW

**Comment by ntindle** [comment]
```
INFO:     127.0.0.1:51226 - "PUT /api/graphs/3f0baa7f-0a91-48bb-ae74-79ad0ef22d22 HTTP/1.1" 200 OK



2024-11-06 16:12:11,434 ERROR  Error in add_execution: Node AIListGeneratorBlock #538ee5a8-e878-4fb2-a393-e775964367ac required input missing: `credentials`
Traceback (most recent call last):
  File "/Users/ntindle/code/agpt/AutoGPT/autogpt_platform/backend/backend/util/service.py", line 57, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ntindle/code/agpt/AutoGPT/autogpt_platform/backend/backend/executor/manager.py", line 751, in add_execution
    graph.validate_graph(for_run=True)
  File "/Users/ntindle/code/agpt/AutoGPT/autogpt_platform/backend/backend/data/graph.py", line 232, in validate_graph
    raise ValueError(
ValueError: Node AIListGeneratorBlock #538ee5a8-e878-4fb2-a393-e775964367ac required input missing: `credentials`
INFO:     127.0.0.1:51226 - "POST /api/graphs/3f0baa7f-0a91-48bb-ae74-79ad0ef22d22/execute HTTP/1.1" 400 Bad Request
INFO:     connection closed
```

https://github.com/user-attachments/assets/8f390b97-45c4-442c-a5bd-2e16a29e2614

**Comment by ntindle** [comment]
image

Yeah credentials I think will need some work here so that they are correctly associated, or maybe that's because its graph in same graph. Yeah tested and it's fine in other cases. Weird.



Also pins don't seem to get consumed correctly, but that may be a bigger bug

image

**Review by ntindle — DISMISSED** [review]
Approving assuming you can't replicate

**Review by aarushik93 — DISMISSED** [review]

**Comment by majdyz** [comment]
@ntindle I'll check if I can replicate

**Comment by majdyz** [comment]
@ntindle  I'm not able to repro the credentials issue. for the consumed beads what is the output blocks being used?

**Review by ntindle — APPROVED** [review]

**Pull request merged**
