### PR TITLE
feat(frontend): Update block UI

### PR DESCRIPTION
**Pull request by majdyz**
### Background

This is the revival of https://github.com/Significant-Gravitas/AutoGPT/pull/8190.
With the input-field bug fixed

### Changes 🏗️

Update block UI based on the agreed design.

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

### CODE REVIEW

**Comment by Swiftyos** [comment]
LGTM - I've run through the tests. Though we can no longer test the marketplace features locally

**Comment by majdyz** [comment]
@Swiftyos can you approve it?

**Comment by aarushik93** [comment]
> Though we can no longer test the marketplace features locally

why not? you can change the environment variable to not use the cloud one

**Review by ntindle — DISMISSED** [review]

**Comment by ntindle** [comment]
you need to commit your lock file updates btw

**Review by Bentlybro — APPROVED** [review]
Tested and its all working

**Pull request merged**
