### PR TITLE
Fixing --speak error from docker compose (no module named GI)

### PR DESCRIPTION
**Pull request by cardangi**
Issue:

Exception in thread Thread-1 (speak):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/autogpt/speech/say.py", line 27, in speak
    success = voice_engine.say(text, voice_index)
  File "/app/autogpt/speech/base.py", line 45, in say
    return self._speech(text, voice_index)
  File "/app/autogpt/speech/gtts.py", line 21, in _speech
    playsound("speech.mp3", True)
  File "/usr/local/lib/python3.10/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ModuleNotFoundError: No module named 'gi'

This error was caused because there's not an RUN for the needed packages (which firstly are pycairo and PyGObject).

Other packages are just for good measuring and avoiding other kind of exceptions.

### PR Quality Scorecard ✨

- [ ] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [x] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of Auto-GPT? &ensp; `-5 pts`
  - [x] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Comment by cardangi** [comment]
The issue in case is this one: [(https://github.com/Significant-Gravitas/Auto-GPT/issues/1697)]

**Comment by Pwuts** [comment]
AFAIK Docker doesn't support playing audio anyways, does it?

**Comment by ntindle** [comment]
Turns out docker does support this with a remote pulse audio server

**Comment by Pwuts** [comment]
@ntindle, cool that it's possible, but I don't think that is worth supporting/maintaining right now. TTS is a UI functionality anyway.

**Comment by ntindle** [comment]
Fair let's close

**Pull request closed without merging**
