### PR TITLE
feat(frontend): Add Business Owner Finder Agent

### PR DESCRIPTION
**Pull request by Bentlybro**
### Background

This is to add the Business Owner Finder Agent template to the repo

## Updated video showing latest setup, recorded on 30.09.2024
https://github.com/user-attachments/assets/5f3fe738-8744-4ebb-b52e-34c3e739296e

### Changes 🏗️

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

### CODE REVIEW

**Review by majdyz — COMMENTED** [review]
@Bentlybro is this still a WIP ?
Should we mark this as a draft PR?

**Comment by Bentlybro** [comment]
@majdyz yeah good shout i have to do just a few small tweaks to the flow and then this will be good to go after https://github.com/Significant-Gravitas/AutoGPT/pull/8162, converting to draft for now

**Review by Swiftyos — DISMISSED** [review]
Great Agent!

**Comment by ntindle** [comment]
Can we close this?

**Comment by Bentlybro** [comment]
yeah we can do :)

**Pull request closed without merging**
