### PR TITLE
docs: AI Companion Integration

### PR DESCRIPTION
**Pull request by nickscamara**
### Background

Hey team,

I've been a big fan of AutoGPT and agents in general since the beginning.

Recently, we have been playing around with AutoGPT/Agents and I thought it would be awesome to integrate a Mendable AI companion into your docs. So, I went ahead and implemented it similar to how we implemented it in Langchain, Snapchat, and Llama index.

This can give you the data you need to improve the docs and also get some visibility on what users are asking and wondering about.

Ps. I even did a little 🐙 animation that matches the logo, hope you like it!

Here is a demo video of the implementation: https://www.youtube.com/watch?v=Nb299ahQJEU

Please let me know any changes, or suggestions that you might have. It would be super awesome to implement with you all.

Hopefully, you like it!

A bit more background: I am one of the co-founders of Mendable.ai. We are supporters of open-source projects and we'd love to offer Mendable at no cost.

### Changes 🏗️

- Implements an animated AI companion on the bottom right of the documentation page that answers users' questions about the AutoGPT docs.

### CODE REVIEW

**Comment by nickscamara** [comment]
Hey yall, was wondering if you got a chance to look at this. Would love some feedback :)

@Pwuts

**Comment by Pwuts** [comment]
I love this! @Bentlybro can I ask you to evaluate this feature and decide whether we can merge it now or only after revising the docs?

**Comment by Bentlybro** [comment]
I really like the idea of this and think it will be useful, id like to do some testing with it and ask it some questions to see how well it works, I think we should merge it after we have updated the docs so all the info is up to date.
@nickscamara can i ask what data has been ingested so far?

**Comment by nickscamara** [comment]
Awesome! Super glad y'all liked it! Right now it is trained on your [docs](https://docs.agpt.co/) pages and I can set it up to reingest it daily so it always be updated. 

What is the best email that I can send the login information for the dashboard? That way you see the conversations, and workshop the companion.

**Comment by Bentlybro** [comment]
@nickscamara perfect that sounds really good! do you have discord by any chance? if so can you add me: bentlybro 
Id much rather send the email in DM so its more private if that's ok with you and I think it will be good to be in contact on there too

**Comment by Bentlybro** [comment]
Going to close this as we have added it!

**Comment by Pwuts** [comment]
Yup, it was just added in #5441. Thanks @nickscamara!

**Pull request closed without merging**
