### PR TITLE
Arena submission aware agent

### PR DESCRIPTION
**Pull request by LuisLechugaRuiz**
### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Review by Swiftyos — DISMISSED** [review]

**Comment by Swiftyos** [comment]
Hi @LuisLechugaRuiz I just ran a script that automatically updated your githash to latest. Please can you check it is the correct hash you would like to have assessed. 

If it isn't can you fix the merge conflict please

**Comment by LuisLechugaRuiz** [comment]
Solved @Swiftyos  It should be pointing to this commit https://github.com/LuisLechugaRuiz/AwareAgent/commit/c180063dde49af02ed95ec4c019611da0a5540d7! Thank you

**Comment by LuisLechugaRuiz** [comment]
@Swiftyos can we update the commit until tomorrow 18:00 CET? I would like to fix some small bugs to make it more robust before final submission if possible

**Comment by Bentlybro** [comment]
no you are not allowed to make any more changes, the time thats set for tomorrow is for people who wernt able to submit at the cut off time/are in diffrent time zones.

**Comment by LuisLechugaRuiz** [comment]
Thank you @Bentlybro. Can we merge this? Is my final commit (was performed at 12:00 CET)

**Comment by Bentlybro** [comment]
> Thank you @Bentlybro. Can we merge this? Is my final commit (was performed at 12:00 CET)

@Swiftyos will be able to merge this when they are next available

**Comment by Swiftyos** [comment]
Hi @LuisLechugaRuiz I will merge it but there is a chance our automated system will use the last commit you made before 12:00 CET. Given this was 10mins outside the window we may allow it - it's on a case by case basis and depends on what was changed in the commit

**Pull request merged**
