### PR TITLE
Added setting for LocalLLMs/other URLs, integration tests failing

### PR DESCRIPTION
**Pull request by kiljoy001**
### Background
Many users have been asking for a local LLM support for this project. This PR enables that.

### Changes
I've added  2 new settings in the template,  LOCAL_LLM_ENABLED, and 
LLM_URL. In config.py, new logic to detect LOCAL_LLM_ENABLED, and if so, update openai.base_url to what is set in LLM_URL

### Documentation
Code in config.py has comments for each line describing what it does.
### Test Plan
Using the current tests - unit tests pass, however intergration tests are failing. I will continue to work on getting them into a passing state.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [ ] I have run `black .` and `isort .` against my code to ensure it passes our linter.

I have not added any new test because
a) I am new to this project
b) the functionality of changing the URL base should not mean changes to most code. However, since the local I am using (GPT4All) does not have embedding included in it's API at this time.

### CODE REVIEW

**Comment by Wladastic** [comment]
This will not really work unless you have openai servers running locally.
This plugin works pretty well though:
https://github.com/danikhan632/Auto-GPT-Text-Gen-Plugin

**Comment by kiljoy001** [comment]
That was the whole point of this - to use a LOCAL llm.

**Review by ntindle — CHANGES_REQUESTED** [review]
Needs discussion

**Comment by Wladastic** [comment]
Have you tested this to work with GPT4ALL?
I found a few plugins for both Dalai and oobabooga, but GPT4ALL I have never tested it.

**Pull request closed without merging**
