### PR TITLE
fixes #7198

### LINKED ISSUE #7198: File paths for images in forge docs are out of date
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Documentation

### Describe your issue.

1. Go to https://github.com/Significant-Gravitas/AutoGPT?tab=readme-ov-file#-building-blocks
2. Click [Getting Started with Forge](https://github.com/Significant-Gravitas/AutoGPT/blob/master/forge/tutorials/001_getting_started.md)
3. The images in the Markdown file are broken

### Upload Activity Log Content

_No response_

### Upload Error Log Content

_No response_

### PR DESCRIPTION
**Pull request by vasnt**
### Changes 🏗️

/ replaced by %F in image file path

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? [7198](https://github.com/Significant-Gravitas/AutoGPT/issues/7198) &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

___

### **PR Type**
Bug fix, Documentation

___

### **Description**
- Fixed image file paths in multiple tutorial markdown files by replacing '/' with '%2F' to ensure proper image display.
- Updated image links in 'Getting Started', 'Blueprint of an Agent', and 'Crafting Agent Logic' tutorials to use the encoded path format.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>001_getting_started.md</strong><dd><code>Fix image paths in 'Getting Started' tutorial</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

forge/tutorials/001_getting_started.md

<li>Updated image file paths by replacing '/' with '%2F' to ensure proper <br>display.<br> <li> Modified multiple image links to use the encoded path format.<br>

</details>

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7593/files#diff-c60532ef6e8a97fad43c17f127ea56de1ae660017aa13af3a67e6f9782219315">+11/-11</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>002_blueprint_of_an_agent.md</strong><dd><code>Fix image paths in 'Blueprint of an Agent' tutorial</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

forge/tutorials/002_blueprint_of_an_agent.md

<li>Corrected image file paths by replacing '/' with '%2F' to ensure <br>images display correctly.<br> <li> Adjusted several image links to use the encoded path format.<br>

</details>

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7593/files#diff-81d6e3bac8dc587818ac8b00d3119ae2b73cc0965ef88dc736c7b5658ceacf24">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>003_crafting_agent_logic.md</strong><dd><code>Fix image paths in 'Crafting Agent Logic' tutorial</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

forge/tutorials/003_crafting_agent_logic.md

<li>Fixed image file paths by replacing '/' with '%2F' to ensure proper <br>image rendering.<br> <li> Updated multiple image links to use the encoded path format.<br>

</details>

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7593/files#diff-1732b25e571effb20dbde58eec523ec1c5f00f3c2b9c83ea334af688f8fc9724">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by ntindle** [comment]
Not sure why the deploy preview was canceled. @Pwuts ?

**Comment by ntindle** [comment]
Thanks for the contribution! The next step here is to review it and give you feedback. My message above to Pwuts is about a tool we have to make checking changes easier, but it didn't work correctly.

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
JK @Pwuts this isn't in the docs directory

**Comment by Pwuts** [comment]
Hi @vasnt, thanks for noticing and fixing those images! What I don't understand though is *why* this works. :')

`forge/` was moved from `autogpts/forge/` a while ago, which is what broke these links in the first place. They should have been changed from `../../../docs/` to `../../docs/`.

Do you understand why changing them to `..%2F..%2F..%2Fdocs/` fixes the issue?

**Comment by vasnt** [comment]
@Pwuts , i had no idea why it worked logically. But i had seen one of the image was already being displayed correctly & it has %2F in path instead of / so i copied that idea.

**Pull request merged**
