### PR TITLE
feat(platform): Add Debugging Capability for the Admin role to log-in as other users

### PR DESCRIPTION
**Pull request by majdyz**
This will allow easier debugging of user's ad-hoc issues.

### Changes 🏗️

We allow one admin user's tabs to be logged as a defined user ID by setting the session storage `auth.loggedInAsUserId` key. Session storage is used to isolate the logged-in user to only a life-cycle of a single browser tab.

#### For code changes:
- [ ] I have clearly listed my changes in the PR description
- [ ] I have made a test plan
- [ ] I have tested my changes according to the test plan:
  
  - [ ] ...

<details>
  <summary>Example test plan</summary>
  
  - [ ] Create from scratch and execute an agent with at least 3 blocks
  - [ ] Import an agent from file upload, and confirm it executes correctly
  - [ ] Upload agent to marketplace
  - [ ] Import an agent from marketplace and confirm it executes correctly
  - [ ] Edit an agent from monitor, and confirm it executes correctly
</details>

#### For configuration changes:
- [ ] `.env.example` is updated or already compatible with my changes
- [ ] `docker-compose.yml` is updated or already compatible with my changes
- [ ] I have included a list of my configuration changes in the PR description (under **Changes**)

<details>
  <summary>Examples of configuration changes</summary>

  - Changing ports
  - Adding new services that need to communicate with each other
  - Secrets or environment variable changes
  - New or infrastructure changes such as databases
</details>

### CODE REVIEW

**Comment by aarushik93** [comment]
What's the aim of this & how does it work?

**Comment by majdyz** [comment]
@aarushik93 The aim is as defined in the PR description.

The way it works (for now) is we simply run `sessionStorage.set("auth.loggedInAsUserId", "USER_ID_HERE")` on the console and open the monitor page or refresh the page.

This will allow the admin to debug other users graph, check its execution result, and schedule through the platform instead manually constructing graph from a DB or hitting internal API within VPC.

**Comment by aarushik93** [comment]
But what's stopping malicious actors doing the same then?

**Comment by majdyz** [comment]
The same thing stopping malicious actors from logging in as admin

**Comment by majdyz** [comment]
@ntindle 
Discussed with @aarushik93 we might want to hold this off.

**Pull request closed without merging**
