### PR TITLE
ZEROAGPT_03 entering the arena

### PR DESCRIPTION
**Pull request by risingsunomi**
### 🌟 Welcome to the AutoGPT Arena Hacks Hackathon! 🌟

Hey there amazing builders! We're thrilled to have you join this exciting journey. Before you dive deep into building, we'd love to know more about you and the awesome project you are envisioning. Fill out the template below to kickstart your hackathon journey. May the best agent win! 🏆

#### 🤖 Team Introduction

- **Agent Name:** zeroGPT
- **Team Members:** [Vincent Castro, Lead Engineer/Founder](https://github.com/risingsunomi)
- **Repository Link:** [shamantechnology/TheAgency](https://github.com/shamantechnology/TheAgency)

#### 🌟 Project Vision

- **Starting Point:** We are building from scratch with our knowledge from working with agents in langchain. Following the agent protocol flow and forge setup

- **Preliminary Ideas:** Currently looking to build an agent from the forge template focusing initially on general tasks
  
#### 🏆 Prize Category

- **Target Prize:** We love the idea of code excellence so aiming for that along with the generalist
- **Why this Prize:** Initial seed for our small startup and exposure of our technology and capabilities. We also look to attract talent to help build.

#### 🎬 Introduction Video

- **Video Link:** COMING SOON

#### 📝 Notes and Compliance

- **Additional Notes:** Nothing else
- **Compliance with Hackathon Rules:** WILL DO

#### ✅ Checklist

- [X] We have read and are aligned with the [Hackathon Rules](https://lablab.ai/event/autogpt-arena-hacks).
- [X] We confirm that our project will be open-source and adhere to the MIT License.
- [X] Our lablab.ai registration email matches our OpenAI account to claim the bonus credits (if applicable).

### CODE REVIEW

**Comment by ntindle** [comment]
Hey! Re open this with only the one file changed

**Comment by ntindle** [comment]
@Swiftyos do you know what happened here?

**Comment by risingsunomi** [comment]
> Hey! Re open this with only the one file changed

So only agent.py should be changed? Sorry don't understand the ask here. When I added to the arena it pushed all this automatically.

**Comment by ntindle** [comment]
I’ll ping @Swiftyos and make sure it’s all setup correctly. I’ll reopen for now

**Comment by SilenNaihin** [comment]
Hi! Could you resubmit without all of the code changes, just the entering of the arena through the json? It should just be the below which you have in this pull request
```
{
    "github_repo_url": "https://github.com/shamantechnology/TheAgency",
    "timestamp": "2023-09-30T05:18:13.652705",
    "commit_hash_to_benchmark": "829e8d57e5dc55652583d10e59487147b5afeff3",
    "branch_to_benchmark": "master"
}
```

**Comment by risingsunomi** [comment]
> Hi! Could you resubmit without all of the code changes, just the entering of the arena through the json? It should just be the below which you have in this pull request
> 
> ```
> 
> {
> 
>     "github_repo_url": "https://github.com/shamantechnology/TheAgency",
> 
>     "timestamp": "2023-09-30T05:18:13.652705",
> 
>     "commit_hash_to_benchmark": "829e8d57e5dc55652583d10e59487147b5afeff3",
> 
>     "branch_to_benchmark": "master"
> 
> }
> 
> ```

Yes will work on this today. So will try to remove this/delete it and resubmit with the json

**Pull request closed without merging**
