### PR TITLE
Add reCAPTCHA and 'I am not a robot' check to web scraper. Related to issues #2293

### PR DESCRIPTION
**Pull request by nanaofosu**
… issues #2293

### Background

This pull request adds a check for CAPTCHA or "I am not a robot" to the Selenium web scraper in order to address the issue of human blocking. Previously, the scraper would continue to run despite such checks, leading to inaccurate results. This enhancement ensures that the scraper can collect accurate data from the website.

### Changes

The scrape_text_with_selenium function in the selenium_scraping.py module was modified to add a check for CAPTCHA or "I am not a robot" by searching for those strings in the page source. If either string is found, the code pauses execution and prompts the user to complete the check before continuing. This change ensures that the scraper can accurately collect data from websites that have human blocking in place.

### Documentation

The changes are documented in the code using comments that describe the purpose and functionality of the added check. Additionally, this pull request includes documentation in the form of a README file that explains how to use the web scraper and how to contribute to the project.

### Test Plan

To test this functionality, we ran the web scraper on several websites that have CAPTCHA or "I am not a robot" checks in place. In each case, the scraper paused execution and prompted the user to complete the check before continuing. We also tested the scraper on websites without such checks to ensure that the functionality was not impacted by the added check.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by hugo4711** [comment]
Also stupid Cookie Notices need to be ignored too...

**Comment by nanaofosu** [comment]
> Also stupid Cookie Notices need to be ignored too...

@hugo4711 
Can you try this and let me know if it works? I am at work so I can't test it.
```# Check if "captcha" or "i am not a robot" or "cookie" is in the page source
    if "captcha" in driver.page_source.lower() or "i am not a robot" in driver.page_source.lower() or "cookie" in driver.page_source.lower():
        try:
            accept_cookies_button = driver.find_element_by_xpath("//button[contains(text(), 'Accept') or contains(text(), 'I accept') or contains(text(), 'Agree') or contains(text(), 'OK')]")
            accept_cookies_button.click()
        except:
            pass
        input("Please complete the CAPTCHA, 'I am not a robot' check, or accept the cookies and press Enter to continue...")```

**Comment by hugo4711** [comment]
@nanaofosu Could you pinpoint me where I need to put that code?

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by anonhostpi** [comment]
A better alternative to this would be to use Selenium Awaiters instead. That way, you don't have to press "enter" to continue

**Comment by gravelBridge** [comment]
Hey, thanks for the great work! We apologize for not getting to this sooner. Unfortunately, this is now a bit outdated as now by default, the browser starts as headless by default. Could you think of a new implementation?

**Comment by ntindle** [comment]
@nanaofosu do you plan on updating this as requested by @gravelBridge ?

**Comment by ntindle** [comment]
blocked: Needs updated to support headless

**Pull request closed without merging**
