### PR TITLE
Fixed revising constraints and best practices

### PR DESCRIPTION
**Pull request by ThunderDrag**
### Background
When using AutoGPT I noticed that it starts to skip constraints and best practices when you use "-" to remove them, it seems like that happens because the constraints are removed in the for loop immediately thus shortening the list and skipping over other constraints.

### Changes 🏗️
I have made an list for constraints and best practices each, the ones designated for removal are added to that list and removed after the for loop has finished

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Comment by Pwuts** [comment]
You're right about the bug, a `for` loop doesn't like in-place removal of items. Nice catch!

The fix could be a bit simpler though, by turning the `for` loop into a `while` loop, like here:
https://github.com/Significant-Gravitas/AutoGPT/blob/66e0c87894cf363d6c7d7076be9f7f0686706bec/benchmark/agbenchmark/conftest.py#L247-L266

**Review by Pwuts — CHANGES_REQUESTED** [review]
The fix could be a bit simpler though, by turning the `for` loop into a `while` loop, like this:

```diff
        # Revise constraints
-       for i, constraint in enumerate(directives.constraints):
+       i = 0
+       while i < len(directives.constraints)
+           constraint = directives.constraints[i]
            print_attribute(f"Constraint {i+1}:", f'"{constraint}"')
            new_constraint = (
                await clean_input(
                    app_config,
                    f"Enter new constraint {i+1}"
                    " (press enter to keep current, or '-' to remove):",
                )
                or constraint
            )
            if new_constraint == "-":
                directives.constraints.remove(constraint)
+               continue
            elif new_constraint:
                directives.constraints[i] = new_constraint
+           i += 1
```

**Comment by ThunderDrag** [comment]
Made the requested changes

**Comment by Pwuts** [comment]
Please run `poetry run black . && poetry run flake8 .`: https://github.com/Significant-Gravitas/AutoGPT/actions/runs/7759553508/job/21164192021?pr=6777

**Comment by ThunderDrag** [comment]
I have ran the commands

**Review by Pwuts — CHANGES_REQUESTED** [review]
Diff contains a lot of code formatting changes that are outside the scope of the PR. Please undo them, re-request review, and then I'll take a look.

**Comment by ntindle** [comment]
You can probably revert this commit and try again 2bd8a5033dc2f69298efe7e8b27cb7d697f79386

**Comment by ThunderDrag** [comment]
Rebased it

**Comment by Pwuts** [comment]
Thank you very much :)

**Pull request merged**
