### PR TITLE
fix(server): Add Azure-related environment variables for server

### LINKED ISSUE #7746: [Server]: Deployed Azure instances with endpoints do not run agents
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### What LLM Provider do you use?

Azure

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

4bbbbd6e2153cfbbce38c78b1985aa14a10dccf4

### Describe your issue.

While working with the Builder and adding LLM agent blocks we are not able to work with an Azure deployment of Open AI's 4o or other models.

We followed the guidance in the docs referenced here: [Using a GPT Azure-instance](https://docs.agpt.co/autogpt/setup/#openai) but were not seeing our deployed instances become leveraged.

### Screenshot:
image

### Upload Activity Log Content

_No response_

### Upload Error Log Content

The Server throws this error:

```
[ExecutionManager][graph-eid-90016001-9dc8-474d-acea-23f3033670eb|node-eid-df2a5c8e-2550-4099-a081-41617a51f9fa|-] Finished node execution
Error calling LLM: Connection error.
Error calling LLM: Connection error.
Error calling LLM: Connection error.
[ExecutionManager][graph-eid-90016001-9dc8-474d-acea-23f3033670eb|node-eid-d4512497-458f-4165-b7ff-63380f1d7e7b|TextLlmCallBlock] Executed, output [error]:`exceptions must derive from BaseException`
[ExecutionManager][graph-eid-90016001-9dc8-474d-acea-23f3033670eb|node-eid-d4512497-458f-4165-b7ff-63380f1d7e7b|-] Finished node execution
[ExecutionManager][graph-eid-90016001-9dc8-474d-acea-23f3033670eb|node-eid-*|-] Finished graph execution
```

### PR DESCRIPTION
**Pull request by andrewhooker2**
Included new environment variables for Azure AD token, OpenAI API type, version, and endpoint in the .env.template. This will enable support for Azure services in the AutoGPT server configuration.

### Background
Resolves: #7746 

Our current server configuration lacks support for Azure OpenAI services, preventing users from leveraging Azure-deployed models in the AutoGPT Builder, particularly when working with LLM agent blocks.
This PR adds the necessary environment variables to support Azure services in the AutoGPT server configuration, enabling seamless integration with Azure-deployed OpenAI models.

### Changes 🏗️
Updated `.env.template` to include new environment variables:

Addition of the following required items to our .env.template 
- Azure AD token
- OpenAI API type
- API version
- API endpoint

Next Steps:
- One call out here is that with these added we are still requiring the user to add their api key to each Block. This will be fixed in a following PR and does not align with being atomic here.

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Comment by ntindle** [comment]
Can these not be set via block?

**Comment by ntindle** [comment]
closing as stale, sorry! feel free to reopen when you get time

**Comment by Fame510** [comment]
Appreciate you actually wiring it up. When you run it, two things will make the diff easy to read: the vectors are `fixtures/conformance.json` in the repo, and the hashes are sealed as of SP/1.0.1 (2026-07-30), so you diff against published hashes rather than against my description of them.

One thing I've learned from the last independent run: most disagreements turn out to be scope boundaries, not verdict conflicts. If your occurrence model doesn't represent nonce, circuit state, or an HITL transition, those vectors will read as "no equivalent" rather than a mismatch, and that's fine. The ones I actually want your eyes on are the budget three and the fail-closed malformed-input case.

Post the layers where you disagree even if it's unflattering to SHACKLE. That's the only way this ends up being worth anything to anyone else reading. Would you mind publishing the raw diff rather than a summary?

**Comment by Fame510** [comment]
That's a fair hit and I'll take it. Separating "I had visibility" from "I had control" is the sharper version of what I was trying to say, and the title overreached. What failed in my case was a logging guardrail sitting next to an unconstrained deploy path, not the concept of mediation.

Your line about rejecting the deploy before `terraform apply` runs is exactly the boundary I ended up building to: the decision has to be pre-execution and it has to be able to say no. A layer that observes and annotates is visibility. A layer that returns DENY and the caller cannot proceed is control. The fail-closed rule follows from that, deny what cannot be verified, because a mediation layer that fails open under malformed input has quietly downgraded itself back to visibility.

If you have the appetite, I'd rather stress-test that boundary than defend the title. Where do you think a pre-execution gate still leaves a hole?

**Comment by Fame510** [comment]
That matches what I saw, and it's the distinction I wish I'd led with: a configured guardrail and an enforced one are different products. Config that the runtime is free to ignore is documentation. Would be curious whether you've seen a framework where the gate can actually refuse.

**Pull request closed without merging**
