### PR TITLE
startup menu for ai_settings.yaml to support multiple configurations

### PR DESCRIPTION
**Pull request by bassie661**
### Summary
I created this PR to add support for storing multiple configurations, thus allowing the user to 'create', 'edit', 'view' or 'delete' configurations and have their settings stored in ai_settings.yaml. The ai_settings file now saves configurations as dictionary and if a configuration exists it is showed as a menu option when autogpt is started.

When no configurations are found, or no ai_settings.yaml file, the user get's the usual generate_aiconfig_automatic questions and can choose to either let autogpt create the config from a single input or the user can choose "--manual" to manually input the first configuration. At the end of this process the first configuration is saved in the ai_settings file.
 
Next time when autogpt starts and/or when configurations are found in ai_settings.yaml, the prompt starts-up with the following menu:

image

### Change
- Support storing multiple AI configurations
- Support choose existing AI configuration(s)
- Support create new AI configuration(s)
- Support edit existing AI configuration(s)
- Support view existing AI configuration(s)
- Support delete existing AI configuration(s)
   -> e.g. ai_name, ai_role, ai_goals[], api_budget, plugins
- Support for plugins per AI configuration (add, delete, change), plugins are expected to land with #4089

This PR is big but it was needed to restructure the old and add the new functionality to the '--manual' startup flow while keeping the functionality clear and maintainable.

* Initial plan was to also add support for setting temperature (ai_temp) per AI configuration (add, delete, change) but this clearly needs extra changes, so a separate PR for ai_temp support is needed.
* This is a new approach which rendered #3711 and #4478 obsolete.
* I had to rewrite a lot of parts to keep up with the commits and release of v0.4.0 / v0.4.1 and v0.4.2
* added support for #4666

### Test Plan
- integration\test_setup.py
- unit\test_ai_config.py
- unit\test_config.py
- unit\test_prompt.py

### PR Quality Checklist
[x] My pull request is atomic and focuses on a single change.
    -> mostly true but reworking the old startup prompts was quite complex which inevitably needed more than a single change.

[x] I have thoroughly tested my changes with multiple different prompts.
[x] I have considered potential risks and mitigations for my changes.
[x] I have documented my changes clearly and comprehensively.
[x] I have not snuck in any "extra" small tweaks changes.
[x] I have run the following commands against my code to ensure it passes our linters: black . / isort . / mypy
autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests --in-place

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Added support for storing and managing multiple AI configurations, including plugins.
- Refactored prompt handling to introduce a new interactive menu for configuration management.
- Integrated automatic configuration generation with the new menu system.
- Added comprehensive unit and integration tests for the new features.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>ai_config.py</strong><dd><code>Support for multiple AI configurations with plugins</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
autogpt/config/ai_config.py

<li>Added support for plugins in AI configurations.<br> <li> Introduced methods for loading, saving, and deleting multiple AI <br>configurations.<br> <li> Updated configuration format to support multiple configurations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-d68085a0cc54be18b0824abf121730479d8ebe3378dff65f74ec4b9e6b2dfbe4">+234/-41</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>config.py</strong><dd><code>Added plugin management and ai_settings_filepath</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
autogpt/config/config.py

<li>Added methods to set plugins allowlist and denylist.<br> <li> Introduced ai_settings_filepath attribute.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-374b58ddc439244ab6370d0640a473386c578b5dd33c799b77c8b5e9673201ed">+13/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>main.py</strong><dd><code>Main entry point modifications for configuration management</code></dd></summary>
<hr>
      
autogpt/main.py

<li>Modified main entry point to support new configuration management.<br> <li> Added start_agent_directly function for direct agent start from menu.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-027a8d4e112086e08e096f9ee40d6f1db123b8ef0406b5f01d17dd5523842594">+59/-4</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>prompt.py</strong><dd><code>Refactored prompt handling and configuration management</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
autogpt/prompts/prompt.py

<li>Refactored prompt handling to support new configuration menu.<br> <li> Added functions for managing AI configurations interactively.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-2f86bd836c4cf448ec53f682b5719d1315f9cd221d8e18cb65961acaec44921f">+811/-44</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>setup.py</strong><dd><code>Integrated automatic configuration with new menu system</code>&nbsp; &nbsp; </dd></summary>
<hr>
      
autogpt/setup.py

<li>Removed manual configuration setup.<br> <li> Integrated automatic configuration generation with new menu system.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-3b73fb2db1dc7dab3c93a250a8495c74a46c417b43ca006fb1bf65c643aacad2">+40/-162</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>4 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>test_setup.py</strong><dd><code>Integration tests for configuration management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/integration/test_setup.py

<li>Added integration tests for new configuration management features.<br> <li> Tested various scenarios including creation, deletion, and editing of <br>configurations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-59be2ef9130d57d244ae3b5a3b62b053021ab0e37574c4cd17d939686a90cf34">+765/-39</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>test_ai_config.py</strong><dd><code>Unit tests for AIConfig class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unit/test_ai_config.py

<li>Added unit tests for AIConfig class methods.<br> <li> Tested loading, saving, and deleting configurations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-dea3efc76efdfcc6019d9016a03024e5bc534dca1fe976976e219a5b42853c78">+421/-45</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>test_config.py</strong><dd><code>Unit tests for plugin management in Config class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unit/test_config.py

<li>Added unit tests for new plugin management methods in Config class.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-217a439192bc495c66132a58a1bf7a92ee70f0eb9702c6b00f60644e726479b5">+30/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>test_prompt.py</strong><dd><code>Unit tests for prompt handling functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
tests/unit/test_prompt.py

<li>Added unit tests for prompt handling functions.<br> <li> Tested validation and management of AI names.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/4646/files#diff-544e7fcafd58b9accfc1b97f09731e216829cd80af965a5d17c6b105f6228ffa">+162/-0</a>&nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by ntindle** [comment]
Looking at the code for this, is it worth it to even convert the existing ones or should we just say copy them out? I don't love breaking backwards compatibility but also don't want users to expect it at this point in the library's lifecycle

**Comment by bassie661** [comment]
same, thanks for nothing

**Comment by Swiftyos** [comment]
@bassie661 the PR looked stale to me. Apologies, I've reopened

**Comment by Swiftyos** [comment]
@bassie661 are you planning on picking this up again?

**Comment by bassie661** [comment]
Nope sorry.

Greets Rob
________________________________
Van: Swifty ***@***.***>
Verzonden: vrijdag 5 juli 2024 10:21
Aan: Significant-Gravitas/AutoGPT ***@***.***>
CC: Rob Jonas ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Significant-Gravitas/AutoGPT] startup menu for ai_settings.yaml to support multiple configurations (PR #4646)


@bassie661<https://github.com/bassie661> are you planning on picking this up again?

**Comment by Swiftyos** [comment]
Okay no worries, closing now then.

**Pull request closed without merging**
