### PR TITLE
Add image-to-text command using Hugging Face API

### PR DESCRIPTION
**Pull request by gucky92**
### Background
Addition of a image description/summary command that uses the huggingface inference API to call a image to text model. Mainly intended when not using GPT4, but GPT3.5.

### Changes
Added a new python file called image_text.py that contains the summarize_image function, which call the huggingface API. 
Made changes to prompt.py, the env template, config.py, and commands.py to include the summarize_image function and make it functional. 

### Documentation
The changes are implemented as just in code comments. 

### Test Plan
I tested the changes by added various image to the working directory or making the autogpt copy images  from the web into the working directory. Then I asked the agent to summarize the images, and create a story.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by nponeccop** [comment]
@gucky92 There are conflicts

**Comment by gucky92** [comment]
Thank you @nponeccop! I resolved the conflicts to be inline with the new structure of the project.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Pwuts** [comment]
@gucky92 any chance you could add an integration test for this functionality?

**Comment by gucky92** [comment]
@Pwuts I haven't worked on this repo for a bit, but I will try to get an integration test committed over the weekend

**Comment by gucky92** [comment]
@Pwuts I have added a basic integration test. Currently in the test I load images into the workspace; i don't know if we want to save test images in the repo or do this some other way. There are also other tests we could add similar to the generate_image tests for example.

**Comment by Swiftyos** [comment]
Closing old PRS

**Pull request closed without merging**
