### PR TITLE
feat(platform): Add delete agent functionality

### PR DESCRIPTION
**Pull request by majdyz**
### Background

We are not able to remove an agent.

### Changes 🏗️

Added UI & API for deleting an Agent.

image
image

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

### CODE REVIEW

**Review by Swiftyos — DISMISSED** [review]
Just wanted to point out that using TypedDict is causing some issues since our Docker image is based on Python 3.11. Pydantic doesn’t fully support typing.TypedDict in versions below Python 3.12, which is why we're seeing those errors.

To fix this, we need to replace from typing import TypedDict with from typing_extensions import TypedDict. This should make it compatible with our current setup.

**Comment by aarushik93** [comment]
@Swiftyos why don't we just update the docker image?

**Comment by aarushik93** [comment]
this clashes with https://github.com/Significant-Gravitas/AutoGPT/pull/8272. I can close my PR or you can remove the migrations from yours and use the ones i created

**Comment by Swiftyos** [comment]
> @Swiftyos why don't we just update the docker image?

Both are valid options - I'll let @majdyz decided if he wants to include upgrading the docker image python version in this.

**Comment by aarushik93** [comment]
@majdyz if you upgrade docker files lets do it in a diff PR please

**Comment by majdyz** [comment]
@aarushik93 I can remove the change on my end, would you mind to add some of the changes I added on my PR if it's not there already on your PR?

**Comment by aarushik93** [comment]
@majdyz yeah sure thing - what changes would you like added?

**Comment by majdyz** [comment]
@aarushik93 nvm ur pr has been auto merged :)

**Review by aarushik93 — APPROVED** [review]

**Review by ntindle — APPROVED** [review]

**Pull request merged**
