### PR TITLE
Add GPT-4o Mini model to OpenAI provider

### PR DESCRIPTION
**Pull request by radleta**
### Background

The addition of the GPT-4o Mini model to the OpenAI provider will enhance the application's capabilities by providing a model with a higher token limit and support for the function call API. This is necessary for users requiring extensive token usage and advanced API functionalities.

Link to the issue: [Add gpt-4o-mini #7479](https://github.com/Significant-Gravitas/AutoGPT/issues/7479)

### Changes 🏗️

This pull request includes:
- Adding the GPT-4o Mini model to the OpenAI provider in the `openai.py` file.
  - Prompt token cost: 0.15/1,000,000
  - Completion token cost: 0.6/1,000,000
  - Maximum token limit: 128,000
  - Support for function call API

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

___

### **PR Type**
Enhancement

___

### **Description**
- Added the GPT-4o Mini model to the OpenAI provider in the `openai.py` file.
- Defined new model names `GPT4_O_MINI_v1`, `GPT4_O_MINI_ROLLING`, and `GPT4_O_MINI`.
- Set prompt token cost to 0.15/1,000,000 and completion token cost to 0.6/1,000,000 for GPT-4o Mini.
- Established a maximum token limit of 128,000 for GPT-4o Mini.
- Enabled support for the function call API for the GPT-4o Mini model.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>openai.py</strong><dd><code>Add GPT-4o Mini model to OpenAI provider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

forge/forge/llm/providers/openai.py

<li>Added new GPT-4o Mini model to the OpenAI provider.<br> <li> Defined new model names and mapping for GPT-4o Mini.<br> <li> Set token costs and maximum token limit for GPT-4o Mini.<br> <li> Enabled function call API support for GPT-4o Mini.<br>

</details>

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7694/files#diff-8ad06a400003efdd02abe8e5983a6f44468fe9abb3cc89103030208033bcd9f5">+12/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by radleta** [comment]
> ## PR Code Suggestions ✨
> Category	Suggestion                                                                                                                                   	Score
> **Maintainability**	
> Standardize the naming convention for model identifiers
> **Consider using a consistent naming convention for the model identifiers. The new model identifier `GPT4_O_MINI_v1` uses both uppercase and lowercase with an underscore and a hyphen, which is inconsistent with other model identifiers that use only uppercase and underscores.**
> 
> [forge/forge/llm/providers/openai.py [79]](https://github.com/Significant-Gravitas/AutoGPT/pull/7694/files#diff-8ad06a400003efdd02abe8e5983a6f44468fe9abb3cc89103030208033bcd9f5R79-R79)
> 
> ```diff
> -GPT4_O_MINI_v1 = "gpt-4o-mini-2024-07-18"
> +GPT4_O_MINI_V1 = "gpt-4o-mini-2024-07-18"
>  
> ```
> 
> * [ ]  **Apply this suggestion**
> 
> Suggestion importance[1-10]: 8
> 8

This suggestion isn't consistent with the casing of the other model names. They use lower case "v1" not "V1" as recommended.

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
@Pwuts do you know anything about this chromedriver error?

**Comment by Pwuts** [comment]
@ntindle looks like dark magic to me

**Comment by vishesh10** [comment]
Hey @ntindle @Pwuts,
I have created the PR to address this chromedriver issue along with the support for GPT-4o mini model.
https://github.com/Significant-Gravitas/AutoGPT/pull/8007

Thanks

**Comment by ntindle** [comment]
superseeded by #8007

**Pull request closed without merging**
