### PR TITLE
feat(builder): Store and display output data history in nodes

### PR DESCRIPTION
**Pull request by kcze**
### Background

Ticket: https://github.com/Significant-Gravitas/AutoGPT/issues/7898

### Changes 🏗️

Nodes retain all execution data from the current run. Results are viewable in a table with related execution ids, and can be copied using a button displayed on hover.
Screenshot 2024-08-30 at 2 31 31 PM

- Update styling and use tailwind more
- Add `react-toast` dependency
- Fix output button not changing checked state on execution
- Make status a badge in node's corner
- Rename `output_data` to `executionResults` and store multiple results with execution UUIDs
- Add `DataTable` component that displays execution outputs
- Outputs can be copied and there's a toast displayed as a feedback

### CODE REVIEW

**Comment by majdyz** [comment]
🔥 
Feedback from my end:

image

1. This will show only 1 row per execution, I think we need to show only one row per output, instead of dumping all of them as a list in a single row.

2. For debugging & customer support purposes, I think it will be much more useful to show maybe first 8 characters of its node execution on the `Execution` title, otherwise we won't know which one is which.

3. Why do we need a clear button? Can it just be auto-clear for each graph execution?

**Comment by kcze** [comment]
> 1. This will show only 1 row per execution, I think we need to show only one row per output, instead of dumping all of them as a list in a single row.

Now one bead = one row. I think it'd be more confusing if we split one result (one bead) into multiple rows but I still can do this. If `List Iterator` outputs a single list then that seems correct, if it yielded multiple separate values (beads) then you'd have multiple rows.

> 2. For debugging & customer support purposes, I think it will be much more useful to show maybe first 8 characters of its node execution on the `Execution` title, otherwise we won't know which one is which.

I'll make it so it shows execution uuids.

> 3. Why do we need a clear button? Can it just be auto-clear for each graph execution?

I was under impression that we wanted to retain all data executions across all runs but now I think maybe all misunderstood and we only need all executions during *one* run.

**Review by majdyz — DISMISSED** [review]
LGTM 🔥🔥🔥

Btw what was the issue with yielding multiple values?

**Comment by ntindle** [comment]
I built a data table component for one of my PRs that’s open. Maybe that would clarify  the above concern

**Comment by kcze** [comment]
> Btw what was the issue with yielding multiple values?

Output is always a table and bead code assumes there's always going to be only one element.

> I built a data table component for one of my PRs that’s open. Maybe that would clarify the above concern

I've seen it, I'm going to merge as is and you can swap/update if you wish.

**Pull request merged**
