### PR TITLE
feat(agent): add jupyter support

### PR DESCRIPTION
**Pull request by MKdir98**
### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Comment by ntindle** [comment]
I think this is a good start! Would love a Jupyter notebook file with access to autogpt’s loop for modifications and code complete for the issue

**Comment by MKdir98** [comment]
> I think this is a good start! Would love a Jupyter notebook file with access to autogpt’s loop for modifications and code complete for the issue

I was just thinking and I think it's good we have a folder as notebooks in agents folder.
It should be in gitignore. we can put some examples. Can we do that?

**Comment by MKdir98** [comment]
I pushed a notebook and add some example of how we can work with it. https://github.com/Significant-Gravitas/AutoGPT/pull/6809/files#diff-e5fc957a7351f7a6fc4ca9edf51a394d305ed1e02068c6887a8f81d73f4e42db

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
@Pwuts ready for review. Goal is an initial example of notebook in repo, then AutoGPT in one

**Comment by MKdir98** [comment]
I fixed lint and pushed it again

**Comment by Pwuts** [comment]
A few initial notes:
* Please fill out the PR description template. That way we don't have to guess about the goal and thoughts behind the PR.
* The core objective of #5132, which this PR seems to revolve around, is to make the Python environment available to the agent persistent.

**Review by Pwuts — COMMENTED** [review]
A Jupyter notebook can be part of an implementation for #5132 (see comment above). That being said, this PR doesn't address the actual integration with the agent.

Using Jupyter notebooks for quick prototyping and development is definitely useful! But: this should need minimal setup in the repo itself. VSCode has [near-builtin support](https://code.visualstudio.com/docs/datascience/jupyter-notebooks) for editing Jupyter notebooks, and there's also Google Colab which allows working on notebooks in git repos.

**Comment by MKdir98** [comment]
> A Jupyter notebook can be part of an implementation for #5132 (see comment above). That being said, this PR doesn't address the actual integration with the agent.
> 
> Using Jupyter notebooks for quick prototyping and development is definitely useful! But: this should need minimal setup in the repo itself. VSCode has [near-builtin support](https://code.visualstudio.com/docs/datascience/jupyter-notebooks) for editing Jupyter notebooks, and there's also Google Colab which allows working on notebooks in git repos.

Oh sorry. I just misunderstood this one. I read the issue again, and now I understand it. Let me investigate more about the main task.

**Pull request closed without merging**
