### PR TITLE
fix(backend): Fix iteration and timer block

### PR DESCRIPTION
**Pull request by majdyz**
### Background

Improvement on the Step Through Items & Timer block.

### Changes 🏗️

* Avoid mixing data types for items input on Step Through Items block.
* Make input pins on CountDownTimer block non-advanced.

Only for the new autogpt platform, currently in autogpt_platform/

- Create from scratch and execute an agent with at least 3 blocks
- Import an agent from file upload, and confirm it executes correctly
- Upload agent to marketplace
- Import an agent from marketplace and confirm it executes correctly
- Edit an agent from monitor, and confirm it executes correctly

Only for the new autogpt platform, currently in autogpt_platform/

If you're making configuration or infrastructure changes, please remember to check you've updated the related infrastructure code in the autogpt_platform/infra folder.

Examples of such changes might include: 

- Changing ports
- Adding new services that need to communicate with each other
- Secrets or environment variable changes
- New or infrastructure changes such as databases

### CODE REVIEW

**Review by ntindle — DISMISSED** [review]
I agree with the changes here, but we need to figure out migration routes for these type of changes in general. Can you check the marketplace for these being used? if not problematic, feel free to merge

**Comment by majdyz** [comment]
@ntindle good point, I don't see it being used at all in the marketplace, but I can see some historical graphs using it. So I reverted the breaking change.

**Comment by Torantulino** [comment]
Is this compatible with loading graphs that have the old version of the block in it now?
Since you've (just) added inputs I wonder whether it will break the graphs or not.

Nick is right that we need to not break blocks until we implement block versioning.

**Comment by majdyz** [comment]
The added input is not mandatory, so it's not going to break the old block

**Comment by majdyz** [comment]
The only case that it might break is if there is a graph that uses `item` input but as str not as list

**Comment by majdyz** [comment]
Superseded by: https://github.com/Significant-Gravitas/AutoGPT/pull/8713

**Pull request closed without merging**
