### PR TITLE
Fixing support for AzureOpenAI

### PR DESCRIPTION
**Pull request by edwardsp**
### Background

The latest master branch is not working for AzureOpenAI

### Changes 🏗️

When listing models it was not even considering AzureOpenAI but for other calls it was passing `******`instead of the
argument as it was using SecretStr.

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Review by Pwuts — CHANGES_REQUESTED** [review]
Unmasking the secrets should be handled in `OpenAICredentials.get_api_access_kwargs`. I see `azure_endpoint` isn't being handled properly in that function.

The fix:
image

**Comment by Pwuts** [comment]
[❌ **AutoGPT Python CI / lint (pull_request)** &ensp; Failing after 1m](https://github.com/Significant-Gravitas/AutoGPT/actions/runs/8093851129/job/22117326165?pr=6927)

Please run `isort .` and `black .`

**Review by Pwuts — APPROVED** [review]

**Comment by Pwuts** [comment]
Thank you @edwardsp!

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️

**Pull request merged**
