### PR TITLE
Add FastChat API for local models.

### PR DESCRIPTION
**Pull request by BillSchumacher**
This adds a working dockerized setup for FastChat local models. They appear to use an OpenAI compliant URL scheme:
image

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by BillSchumacher** [comment]
Need to add config options, add chat completion call and documentation.

**Comment by BillSchumacher** [comment]
`docker compose up -f docker-compose-fastchat.yml --build --wait`

**Comment by ntindle** [comment]
Based on discussion with @Torantulino we should expand the plug-in interface to support this rather than putting them in the main repo. 

I see multiple categories of plugins coming to exist with some of the obvious being:
- Models
- Memory
- Commands

**Comment by BillSchumacher** [comment]
I was just going to monkey patch the openai url.

**Comment by BillSchumacher** [comment]
Whoever thinks they can make dockerfiles into a plugin feel free.

**Comment by Boostrix** [comment]
> Whoever thinks they can make dockerfiles into a plugin feel free.

sorry, asking for clarification: are you asking for a plugin to generate docker files ?

**Comment by BillSchumacher** [comment]
> > Whoever thinks they can make dockerfiles into a plugin feel free.
> 
> sorry, asking for clarification: are you asking for a plugin to generate docker files ?

No, this PR is just dockerfiles ATM. I was going to finish implementing this as part of the core, which made a lot of sense to me as it would require minimal code changes and is commercially licensable. I might do that on my fork instead.

**Comment by yeserumo** [comment]
hello, what should i do to use FastChat API for AutoGPT

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by BillSchumacher** [comment]
> hello, what should i do to use FastChat API for AutoGPT

You can see how I did this in my fork.

**Comment by Pwuts** [comment]
Since #2594, you can set a custom backend URL through the `OPENAI_API_BASE_URL` env/config variable. This + a container running FastChat should suffice, right?

I think we should be able to add extra docker-compose files with configurations like this. Not sure whether to put those in the project root or some other folder.

**Comment by ntindle** [comment]
Yeah ideally this would exist as a dedicated docker compose

**Pull request closed without merging**
