### PR TITLE
Create Publish Package to TestPyPi

### PR DESCRIPTION
**Pull request by Qoyyuum**
This will help test the python distribution to TestPyPi for each new push to stable and pull request to master, and easily test the end product afterwards.

### Background
There's no easy way to test new master pull requested packages. With this new workflow, we can see the latest changes and pull request to master, uploaded to TestPyPi and test the new package (as long as the version number in pyproject.toml file is incremented properly).

### Changes
Created a new file, pypi-publish.yml as a new pipeline.
A couple of lines in pyproject.toml file to have a working `python -m build` 

### Documentation
Repo owner needs to set a new Repository secret called, `TEST_PYPI_API_TOKEN`. Get the API Token from https://test.pypi.org/
For each new change and about to release a new version, update the pyproject.toml file with a new version and set it up as a new pull request. This will trigger the workflow and upload it to testpypi.

Test the package by `pip install -i https://test.pypi.org/simple/ auto-gpt==<new version number>`

### Test Plan
Tested by running the workflow myself and uploaded to my test account's project. (Now removed)

### PR Quality Checklist
- [X] My pull request is atomic and focuses on a single change.
- [X] I have thoroughly tested my changes with multiple different prompts.
- [X] I have considered potential risks and mitigations for my changes.
- [X] I have documented my changes clearly and comprehensively.
- [X] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Qoyyuum** [comment]
@BillSchumacher since the [production pypi is already up that I can see](https://pypi.org/project/agpt/) would it make sense for this PR to help automate the release or no?

**Comment by Qoyyuum** [comment]
Hi @Pwuts yeah its a little out of date but that's where I was hoping this PR could help test the package in TestPypi repo before releasing to Prod Pypi. Also, hoping to use the same package as where @BillSchumacher uploaded. But baby steps is to try this out to testpypi first. 

And then I could raise a separate PR to also publish to Prod Pypi, including documentation, so that everyone can just have the latest and greatest release feature (as opposed to git pulling from stable branch) via a simple `pip install agpt --upgrade`.

What do you think?

**Comment by ntindle** [comment]
@Qoyyuum have you taken a look at #4604 ?

**Comment by Pwuts** [comment]
@lc0rp @collijk fyi

**Pull request closed without merging**
