### PR TITLE
[WIP] Implement task management system for more structured progress on goals

### PR DESCRIPTION
**Pull request by hunteraraujo**
### Design Document
 https://docs.google.com/document/d/1pHtgK4OaFxy2POColR4nYJ3wemU4XLTEoxTLQunzaU0/edit?usp=sharing

### Background

One issue I have seen while experimenting with AutoGPT is that it will go deep down irrelevant rabbit holes. In order to address this I am experimenting with having a more structured way of organizing tasks.

### Changes

- `TaskManager`: A singleton class responsible for managing tasks, including creating tasks, retrieving tasks by ID, updating task states, and displaying task hierarchy.
- `TaskState`:An enumeration representing the state of a task (NOT_STARTED, IN_PROGRESS, COMPLETED).
- `Task`: A class representing individual tasks with properties like ID, name, state, parent task, and subtasks.
- New `--taskmanager` command line flag to enable and disable
- New commands for managing tasks: `update_task_state` and `set_current_task`

### Test Plan

- Add unit tests for Task Manager, Task, and TaskState

### Outstanding items

- Refine prompt to ensure AutoGPT is always managing tasks
- Allow for programmatically adding task manager portion of prompt based off command line flag

### Change Safety

- [ ] I have added tests to cover my changes
- [ ] I have considered potential risks and mitigations for my changes

### CODE REVIEW

**Comment by onekum** [comment]
What's the status of this? Are you still working on this? Also, I think it would be more fitting to turn this into a draft PR.

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Comment by Boostrix** [comment]
#4107

**Comment by Pwuts** [comment]
@collijk fyi

**Comment by Pwuts** [comment]
I'll be trying to incorporate (something like) this into #4799

**Comment by Swiftyos** [comment]
Closing old PRS

**Pull request closed without merging**
