### PR TITLE
Update README.advanced.md

### PR DESCRIPTION
**Pull request by aaly00**
### **User description**
The copy .env command is wrong. The file name should be `.env.example` instead of `env.example`

### Changes 🏗️

Fixed the command which copies the .env file in the documenation. 

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [x] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

___

### **PR Type**
Documentation

___

### **Description**
- Corrected the `.env` file copy command in the `README.advanced.md` file to use `.env.example` instead of `env.example`.
- Fixed a formatting issue by adding a newline at the end of the file.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>README.advanced.md</strong><dd><code>Fix incorrect .env file copy command and formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

rnd/autogpt_server/README.advanced.md

<li>Corrected the <code>.env</code> file copy command to use <code>.env.example</code> instead of <br><code>env.example</code>.<br> <li> Fixed formatting issue by adding a newline at the end of the file.<br>

</details>

  </td>
  <td><a href="https://github.com/Significant-Gravitas/AutoGPT/pull/7607/files#diff-47a0431dd869386038cdcf9613f91527cfd9d061de87c5af4ccfb1078da49c22">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
@aarushik93 do you know why this isn't able to set the password?

**Comment by ntindle** [comment]
Could we prefer a env based password if available and default/fallback if not?

**Comment by ntindle** [comment]
Is it because they can’t read the environment secrets?

**Comment by aarushik93** [comment]
the contributors can't read our secrets. I'll merge this PR and add one to use default variables

**Pull request merged**
