### PR TITLE
Please do not 'rm -rf <unquoted variable>. Also please do not 'rm -rf' without confirmation, use 'rm -r' instead!

### LINKED ISSUE #7404: agent setup `rm -rf <venv>` ... should warn beforehand.
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4(32k)

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Putting a file called `setup.py` in the main directory, is inviting people to `just run it to see what happens`... and if what happens is that their entire `venv` that might or might not be easily re-creatable just gets wiped, it will not create a good first experience... 

Before such a command is run, it should ask for confirmation. Ie. either remove the `-f`, or explicitly prompt the user or point them in the right direction, or explain why.

### Upload Activity Log Content

_No response_

### Upload Error Log Content

_No response_

### PR DESCRIPTION
**Pull request by dagelf**
### Background

I just did the "tutorial" and thankfully I implemented this change before I did, because I would've been MOST unhappy if this happened:

```
[coenraad@r2t2 AutoGPT]$ ./run agent create test
🎉 New agent 'test' created. The code for your new agent is in: agents/test
[coenraad@r2t2 AutoGPT]$ ./run agent start test
⌛ Running setup for agent 'test'...
Path /home/coenraad/AutoGPT/agents/benchmark for agbenchmark does not exist
Press ENTER to remove /home/coenraad/.venv
^C

$ /usr/bin/du $(poetry env info --path) --max-depth=0 -h|sort -h
14G	/home/coenraad/.venv
```

My connectivity isn't that great, and this environment, being my development environment, has packages accumulated over months. This is not my reproducible production machine, it's my personal dev machine...  maybe I shouldn't try out new projects outside of a sandbox.... but a lot of people do, and this can really bite them.

### Changes 🏗️

Quoted the "$ENV_PATH". Also made sure the script fails, if the rm command fails.
Also added a double confirmation.
Also added a way to skip the confirmation: `touch delete`. We can add that to the docs or any CI, if confirmed safe.

This also closes #7404

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [x] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Comment by dagelf** [comment]
The failing CI test looks like it's unrelated to the change.

**Review by Swiftyos — DISMISSED** [review]
@dagelf I'm glad you caught this before you deleted all your packages!

This bit of code is pretty unused now and the tutorials are well out of date. The forge will be removed soon too.

That said, and to avoid us wiping others env without their knowledge, this is a good idea. Thank you 🙏

**Comment by Swiftyos** [comment]
@kcze Can you check the situation with the forge ci please.

cc: @Pwuts

**Comment by dagelf** [comment]
It there's a CI issue, just touch 'delete' in the directory this is called from to skip the prompts. @kcze cc: @Pwuts

**Comment by kcze** [comment]
Forge CI fail seems unrelated
> It there's a CI issue, just touch 'delete' in the directory this is called from to skip the prompts.

**Comment by ntindle** [comment]
I don't have permissions to make branches on your fork and I'm not comfortable updating your master branch to be inline with ours so I'm going to close this for now as its difficult for me to fix any issues that occur. Feel free to update from master and sync branches and reopen

**Comment by dagelf** [comment]
Updated https://github.com/Significant-Gravitas/AutoGPT/pull/8417

**Pull request closed without merging**
