### PR TITLE
Added Chinese README

### PR DESCRIPTION
**Pull request by XYCode-Kerman**
### Background
Add Chinese README

### Changes
Create README_zh-CN.md

Update README.md

Update README_zh-CN.md

### Documentation
None

### Test Plan
None

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by MDR333** [comment]
nahhh

**Comment by MarKiSS2000** [comment]
Looks like that's for the great amount of people speaking Chinese and willing to  install everything correctly. Why not?

**Comment by p-i-** [comment]
This is a mass message from the AutoGPT core team.
Our apologies for the ongoing delay in processing PRs.
This is because we are re-architecting the AutoGPT core!

For more details (and for infor on joining our Discord), please refer to:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

**Review by GitYohoo — APPROVED** [review]

**Comment by ntindle** [comment]
I've looked at this and realistically we don't have anyone capable of reviewing this. We would need multiple Chinese reading and speaking members of the community to vouch for it. Is there anyone capable of doing that?

**Pull request closed without merging**
