### PR TITLE
Add Sentry.io - Send Error logs to central location for better troubleshooting

### PR DESCRIPTION
**Pull request by richbeales**
### Background
Adds support for Sentry, so we can optionally log our users's errors (and maybe info/warn too) to a cloud database for later analysis / fault finding. ([Discord thread](https://discord.com/channels/1092243196446249134/1109551488214237315))

### TODO
- [ ] We need to consider how best to populate the SENTRY_DSN environment variable. 
- [ ] We need to consider pricing (and how many events we expect)
- [ ] We need to consider whether to hide it behind a feature flag (only turn on when required)
- [ ] We need to consider whether to enable/disable for certain parts of the code (e.g. one week we can target just the memory element, or disable just the LLM element?
- [ ] We need to consider how to communicate to users that we might collect data
- [ ] We need to scrub sensitive data from logs before sending to sentry

### Documentation

https://docs.sentry.io/platforms/python/guides/logging/configuration/options/?original_referrer=https%3A%2F%2Fsentry.io%2F

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes. 
- [x] I have run `black .` and `isort .` against my code to ensure it passes our linter.

### CODE REVIEW

**Comment by ntindle** [comment]
CC: @chadwhitacre

**Comment by Torantulino** [comment]
I've applied here:
https://sentry.io/for/open-source/

**Comment by k-boikov** [comment]
I think that whole process should go through an intermediate step on our own host that the user would go to when they click on "submit bug report" after the program has crashed. Something that would be handled by a this https://github.com/Significant-Gravitas/Auto-GPT/pull/4279

**Comment by bfalans** [comment]
In my opinion a flag, which can be set (to none, <maintainer>, <catalyst>, <contributor>?, <all> for example) to open or close specific parts of our code for error reporting should do the trick. Maintainers can then choose to open or close parts to a group or all people.

As for consent of users, a popup or such before crash asking them whether or not they want to file an error report with checkboxes for consent on the needed items could work.

**Comment by p-i-** [comment]
Cross-referencing https://github.com/Significant-Gravitas/Auto-GPT/issues/3699
In this PR (3 weeks ago) a representative from Sentry offered to involve.

**Comment by Pwuts** [comment]
Branch deleted for security reasons

**Pull request closed without merging**
