### PR TITLE
feat(agent_builder): Add shad/cn UI library

### PR DESCRIPTION
**Pull request by Pwuts**
* Blocks #7317

### Changes
- feat(agent_builder): Add shad/cn + Radix Icons + Tailwind
- move favicon.ico to static folder
- delete empty custominput.css

### CODE REVIEW

**Review by Swiftyos — APPROVED** [review]
LGTM

**Comment by aarushik93** [comment]
Are there any changes needed to run the app now? if so can you please add to the readme

**Comment by aarushik93** [comment]
@Pwuts we were disucssing how to work in parallel here https://discord.com/channels/1126875755960336515/1253305243760984096/1258361900941705256

Please don't merge this pr without removing the changes that affect the builder part -> so the Flow.tsx and it's related css

**Review by aarushik93 — CHANGES_REQUESTED** [review]
Please don't merge this pr without removing the changes that affect the builder part -> so the Flow.tsx and it's related css

**Comment by Bentlybro** [comment]
I reverted the changes made to  flow.tsx and flow.css so this can focus on just importing the libs, ill make branch off this PR to work on adding the UI elements

**Comment by Pwuts** [comment]
> Are there any changes needed to run the app now? if so can you please add to the readme

Afaik no

> Please don't merge this pr without removing the changes that affect the builder part -> so the Flow.tsx and it's related css

done

**Review by aarushik93 — APPROVED** [review]
LGTM

**Pull request merged**
