### PR TITLE
fix(backend): Spin-up Database manager on rest.py

### PR DESCRIPTION
**Pull request by majdyz**
AutoGPT-lib is used in both Rest API & Execution Manager, due to the interdependency of the module, some unexpected infra changes were inferred: `DatabaseManager` service is required in both RestAPI & ExecutionManager

The scope of this PR is to clear this out.

### Changes 🏗️

* Initiated `DatabaseManager` on RestAPI service.
* Removed `DATABASEMANAGER_HOST` settings.

Out of scope:
Decouple DatabaseManager service from RestAPI service, and use direct async prisma query instead.

#### For code changes:
- [ ] I have clearly listed my changes in the PR description
- [ ] I have made a test plan
- [ ] I have tested my changes according to the test plan:
  
  - [ ] ...

<details>
  <summary>Example test plan</summary>
  
  - [ ] Create from scratch and execute an agent with at least 3 blocks
  - [ ] Import an agent from file upload, and confirm it executes correctly
  - [ ] Upload agent to marketplace
  - [ ] Import an agent from marketplace and confirm it executes correctly
  - [ ] Edit an agent from monitor, and confirm it executes correctly
</details>

#### For configuration changes:
- [ ] `.env.example` is updated or already compatible with my changes
- [ ] `docker-compose.yml` is updated or already compatible with my changes
- [ ] I have included a list of my configuration changes in the PR description (under **Changes**)

<details>
  <summary>Examples of configuration changes</summary>

  - Changing ports
  - Adding new services that need to communicate with each other
  - Secrets or environment variable changes
  - New or infrastructure changes such as databases
</details>

### CODE REVIEW

**Comment by majdyz** [comment]
@aarushik93 I decoupled changes of dbmanager from the rest of the change in https://github.com/Significant-Gravitas/AutoGPT/pull/8751, to expedite this fix.

**Review by ntindle — APPROVED** [review]
Some of these changes also match up with moving Supabase credentials provider to backend

**Comment by majdyz** [comment]
@ntindle I think you are referring to https://github.com/Significant-Gravitas/AutoGPT/pull/8751

**Comment by ntindle** [comment]
No there's an open pr to move the credentials providers to the backed

**Comment by ntindle** [comment]
https://github.com/Significant-Gravitas/AutoGPT/pull/8648

**Pull request merged**
