### PR TITLE
ref(classic): Do not 'rm -rf <unquoted variable>' when removing classic env

### LINKED ISSUE #7404: agent setup `rm -rf <venv>` ... should warn beforehand.
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4(32k)

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Putting a file called `setup.py` in the main directory, is inviting people to `just run it to see what happens`... and if what happens is that their entire `venv` that might or might not be easily re-creatable just gets wiped, it will not create a good first experience... 

Before such a command is run, it should ask for confirmation. Ie. either remove the `-f`, or explicitly prompt the user or point them in the right direction, or explain why.

### Upload Activity Log Content

_No response_

### Upload Error Log Content

_No response_

### PR DESCRIPTION
**Pull request by dagelf**
Updated "classic" forge to not accidentally delete my environment without warning. (Updated https://github.com/Significant-Gravitas/AutoGPT/pull/8056)

### Background

I just did the "tutorial" and thankfully I implemented this change before I did, because I would've been MOST unhappy if this happened:

```
[coenraad@r2t2 AutoGPT]$ ./run agent create test
🎉 New agent 'test' created. The code for your new agent is in: agents/test
[coenraad@r2t2 AutoGPT]$ ./run agent start test
⌛ Running setup for agent 'test'...
Path /home/coenraad/AutoGPT/agents/benchmark for agbenchmark does not exist
Press ENTER to remove /home/coenraad/.venv
^C

$ /usr/bin/du $(poetry env info --path) --max-depth=0 -h|sort -h
14G	/home/coenraad/.venv
```

My connectivity isn't that great, and this environment, being my development environment, has packages accumulated over months. This is not my reproducible production machine, it's my personal dev machine...  maybe I shouldn't try out new projects outside of a sandbox.... but a lot of people do, and this can really bite them.

### Changes 🏗️

Quoted the "$ENV_PATH". Also made sure the script fails, if the rm command fails.
Also added a double confirmation.
Also added a way to skip the confirmation: `touch delete`. We can add that to the docs or any CI, if confirmed safe.

This also closes #7404

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [x] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
This is going to be challenging to merge as the CI for the classic is broken since moving it. https://github.com/Significant-Gravitas/AutoGPT/pull/8338

**Comment by dagelf** [comment]
If it's broken, merging this won't break it further ...... at least people following the instructions linked in the original issue won't be able to accidentally wipe their environments.

**Comment by dagelf** [comment]
I will look at the CI if I get a chance though......

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
I went and fixed the ci, once its merged #8338, this can go in

**Comment by ntindle** [comment]
@dagelf I Got this fixed up, so we can merge it! I just need you to sign the CLA :)

**Pull request merged**
